version: '3.7'

services:
    mysql:
        image: mysql:5.7
        restart: on-failure:3
        ports:
            - '3306:3306'
        env_file:
            - .env.dev
        environment:
            TERM: xterm
        volumes:
            - ./docker/db:/var/lib/mysql
        command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--skip-character-set-client-handshake', '--sql-mode=']
        logging:
            options:
                max-size: "4m"

